### ISSUE TITLE
Extended Menu

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#11]
Hi,
first of all thanks for the great extension. Using it I run into one problem. It would be great to get some help.

I try to build a onepager with one more menu link to open in a new tab. So I integrated the link into the partial 'menu.html'. But when I click on the new link (shop) nothing happens although the generated link is perfect and can be opended with a right click (open link in a new tab)

```
<f:if condition="{settings.menu}">
    <nav class="tx-bwrk-onepage-menu"
         {f:if(condition: settings.menuSticky, then:
    'data-sticky')}
    {f:if(condition: settings.menuOffset, then: 'data-offset="{settings.menuOffset}"')}
    {f:if(condition: settings.menuThreshold, then: 'data-threshold="{settings.menuThreshold}"')}
    {f:if(condition: settings.menuScroll, then: 'data-scroll-speed="{settings.menuScroll}"')}
    {f:if(condition: settings.menuUpdateHash, then: 'data-update-hash')}
    >
		<ul>
			<f:for each="{object}" as="page">
				<li class="section_page">
					<f:link.page section="section-id-{page.uid}">{page.title}</f:link.page>
				</li>				
			</f:for>	
			<li class="shop">
					<f:link.page pageUid="3" target="_blank">Shop</f:link.page>			
			</li>			
		</ul>
    </nav>
</f:if>
```

Thanks for any hint.

Hobokens

**Comment by marvinhuebner** [comment]
Hi Hobokens,

Nice to hear that you like our extension. The problem is that the jquery plugin will be applied to all links within the container. I added a filter function to prevent this. I uploaded the version v3.0.12. Update to this version and add the class `bwrk-onepage-external` to your link.

```
<li class="shop">
   <f:link.page pageUid="3" target="_blank" class="bwrk-onepage-external">Shop</f:link.page>         
</li>
```

Your welcome.

Marvin Hübner

**Comment by Hobokens** [comment]
Hi Marvin Hübner,

thanks a lot for the new version. Afer the installation an claring of the cache in the install tool  I checked it on my live system and my local system. The external link works perfectly but the sliding effect is lost on both systems. Clicking on the  menu the change between the different sections is like the change on a 'normal' homepage.

Regards
Hobokens

**Comment by marvinhuebner** [comment]
Hi Hobokens,

sorry for this bug. Pull version 3.0.13 and it will work. Please give me a feedback if it works for you. Thanks!

**Comment by Hobokens** [comment]
Hi Hi Marvin Hübner,
perfect, thanks!

Have a nice evening
Hobokens
