### ISSUE TITLE
Display selection class

### ISSUE THREAD

**Issue by opdgit** [bergwerk/bwrk_onepage#13]
The rendering of the select field "selection-class" for registered pages is broken for typo3 7.6. Using of renderType attribute in $tmp_extpages_columns is required:
<code>
$tmp_extpages_columns = array(
    'tx_bwrkonepage_sectionclass' => array(
        'exclude' => 0,
        'label' => 'Section-Class',
        'config' => array(
            'type' => 'select',
            'renderType' => 'selectSingle',
...
</code>
then all is fine.

**Comment by gerchomat** [comment]
fixed in version 3.0.14
