### ISSUE TITLE
Installation via composer fails

### ISSUE THREAD

**Issue by pquerner** [bergwerk/bwrk_onepage#14]
Installation via composer fails:

`Could not find package bwrk_onepage at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability`

If I define the `minimum-stability` to something else (say "stable") it fails too.

Command:
`composer require typo3-ter/bwrk_onepage`

**Comment by pquerner** [comment]
Probably because no "composer.json" file exists. Could you please add one ?

See https://composer.typo3.org/

**Comment by marvinhuebner** [comment]
Currently bwrk_onepage is no registered composer package. I will register it tomorrow and add a `composer.json` file.

**Comment by pquerner** [comment]
I might give you a PR today which will add support. Currently testing. But its better if the vendor itself requests the package, yes.

**Comment by pquerner** [comment]
Great, thanks! (Whenever you have time for this btw, theres no rush)

**Comment by gerchomat** [comment]
fixed in version 3.0.14
