### ISSUE TITLE
TYPO3 7.6.4 and PHP 7.0.0

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#15]
Hi,

with the constellation above I get the following error:

`#1: PHP Runtime Deprecation Notice: call_user_func_array() expects parameter 1 to be a valid callback, non-static method BERGWERK\BwrkOnepage\UserFunc\Extconf::match() should not be called statically in E:\server\htdocs\my_domain\typo3\sysext\core\Classes\Configuration\TypoScript\ConditionMatching\AbstractConditionMatcher.php line 428`

Regards
Hobokens

**Comment by gerchomat** [comment]
Can you tell me how you have received this error?
In Verseion 7.6.4 it works without error.

**Comment by Hobokens** [comment]
Sorry for answering so late. I get the error in a local xampp installation with php 7.0.4, I just tested it with TYPO3 7.6.9, still the same error message.

Hobokens

**Comment by gerchomat** [comment]
maybe it's an local xampp problem?
i dont' really know .. there is no problem in local mamp on mac.

**Comment by Hobokens** [comment]
I will check it on a live system too.

**Comment by Hobokens** [comment]
I checked it on a live system with TYPO3 7.6.9 and PHP 7.0.6 and got the same error

`PHP Runtime Deprecation Notice: call_user_func_array() expects parameter 1 to be a valid callback, non-static method BERGWERK\BwrkOnepage\UserFunc\Extconf::match() should not be called statically in /www/htdocs/xxx/my-domain/typo3_src-7.6.9/typo3/sysext/core/Classes/Configuration/TypoScript/ConditionMatching/AbstractConditionMatcher.php line 428`

**Comment by Hobokens** [comment]
I checked it on a live system with TYPO3 7.6.10 and PHP 7.0.10 and got no more error.
Thanks for the nice extension!

**Comment by gerchomat** [comment]
sill existing

**Comment by Hobokens** [comment]
The latest version 3.1.2. solved the problem for me.
