### ISSUE TITLE
Menu use hide_nav field

### ISSUE THREAD

**Issue by fabianscholz** [bergwerk/bwrk_onepage#16]
Hi,

its possible to add the hide_nav field function to the menu? I need to hide some pages in the navigation but not in the page.

Thanks for help.

**Comment by marvinhuebner** [comment]
Currently there is no option available.

You can hide some nav types with css `nth-child` selector, but this is very ugly and not dynamic. Or you reference the content elements on another page. But this ideas are only work arounds. I will keep this in my mind, perhaps we can add this in the next version. But feel free and make a PR for this feature.
