### ISSUE TITLE
menu as a dropdown in the main navigation

### ISSUE THREAD

**Issue by enem** [bergwerk/bwrk_onepage#21]
First, the page structure of our project:
- home (1st level)
  - about us (2nd level)
    - tradition (3rd level)
    - numbers & facts (3rd level)
    - ... (3rd level)
  - product (2nd level)
    - ... (3rd level)
    - ... (3rd level)
  - news (2nd level)
    - ... (3rd level)
    - ... (3rd level)
  - contact (2nd level)
    - ... (3rd level)
    - ... (3rd level)

We are using your extension on the pages in the 2nd level (e.g. on the page "about us"). On these pages are the contents from the pages in the 3rd level shown. - These works fine.

The problem is that the menu is displayed in the content area. Our main navigation shows the 2nd level pages - if the user clicks on one of these menupoints appears a dropdown-menu. In the dropdown-menu are the pages of the 3rd level shown. By click on one of these menupoints the user should be redirected to the 2nd level page and the content of the choosen page.

Is there any possibility to solve this issue?

**Comment by danielmaier42** [comment]
@enem sorry for the late response, does this issue still exist? if not we would like to close this one, because it's more like a "how could we implement sth. by using your extension?" than a real bug.
