### ISSUE TITLE
double content with simplegrids

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#24]
Hi,
thanks for the new version 3.1. I tried it with TYPO3 8.7 and 7.6. 

Everything looks great but I got a strange problem. When using the extensions gridelements and simplegrids on top of it in a section of bwrk_onepage I get the content of the simplegrid rows and columns twice. First the content ist without the simplegrid tags and classes and then again with the expected tags and classes (TYPO3 7.6.16 and 8.7)
Without simplegrids (only gridelements) there is no  problem,

With bwrk_onepage v3.013 I didn't have any problems with gridelements and simplegrids (TYPO3 7.6.x) but no chance to run bwrk_onepage with TYPO3 8.6.x.

Regards
Hobokens

**Comment by gerchomat** [comment]
Hi,
we have not yet installed compatibility with simplegrid. That's why we're sorry that it does not work anymore.

We will try to fix it as soon as possible.

**Comment by gerchomat** [comment]
We released https://github.com/bergwerk/bwrk_onepage/tree/v3.1.1 - can you please try it?

**Comment by Hobokens** [comment]
I'm sorry, now there is nearly no more content in the sections and the order of the few content elements seems to be mixed up.

I tested it on a local machine with TYPO3 8.7.

**Comment by gerchomat** [comment]
Ok, then we have to do an explicit test with simplegrids.

**Comment by Hobokens** [comment]
I just tried it on a live system (TYPO3 7.6.16) with the same effect.
I also deactivted all simplegrid content elements and  the extension simplegrids without any effect for the frontend output.

**Comment by gerchomat** [comment]
maybe it is a misconfiguration in your typo3. 
the language-settings are heavy sometimes.

can you send us your configuration package? 
i think the typo3conf-folder and a database-dump is enough

**Comment by Hobokens** [comment]
no problem, it's a small installation at the moment. Can you give me your mail contact?
An alternative would be a teamviewer session.

**Comment by gerchomat** [comment]
Yes of course, you find the mail address in the ext_emconf.php

**Comment by gerchomat** [comment]
i have found the error.
you overwrite the Pages.html partial in your fileadmin template-storage.

we have just modified this template file in version 3.1.1. 
either you remove that template (or typoscript) or you replaced it with the new version.

so it should work

**Comment by Hobokens** [comment]
Thanks a lot, I really missed to check the updated template. Sorry for that.
