### ISSUE TITLE
doesn't work, if "show all sub pages" is activated

### ISSUE THREAD

**Issue by mayospacken** [bergwerk/bwrk_onepage#25]
first of all, thanks building this little extension!

if i check the option "show all sub pages?" in the config tab on the page where i want to use the onepager plugin, there is no content of no subpages printed. if i uncheck this option and choose the subpages by myself it works like charm.

i'm using typo3 v 8.7.1 and your bwrk_onepage 3.1.2
maybe there's a fix so it will be more comfortable to use!

**Comment by cosmonoid** [comment]
I've had the same issue. There seems to be a typo in the OnepageController.php in line 93. The uid of the content element is used as pageUid. 
Changing 
`$pages = $this->getPages($cObjData['uid']);`
to 
`$pages = $this->getPages($cObjData['pid']);`

solves that issue.

**Comment by marvinhuebner** [comment]
We will investigate some time in our open source in the next weeks and we will push a fix for this. 

You could also make a PR to fix this, would be great!

**Comment by danielmaier42** [comment]
Closed by PR #26 - Thanks
