### ISSUE TITLE
Backend-Layouts are ignored

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#30]
Hello,
I just ran into a strange problem (TYPO3 8.7.19, bwrk_onepage 3.1.3). I have created a 2 column backend layout that works completely correctly when I display the page alone. However, if I display the page within the one page, the template belonging to the backend layout is not called. Only the content elements of the page are displayed. This means that all formatting informations are missing.
I have no idea at the moment what might be the reason for this.

**Comment by Hobokens** [comment]
Hi again,
I could solve the problem. It was a misconfiguration by myself.
Regards
Hobokens

**Comment by marvinhuebner** [comment]
> Hi again,
> I could solve the problem. It was a misconfiguration by myself.
> Regards
> Hobokens

@Hobokens as you have deleted this comment and reopened, I assume that your problem is not fixed. Could you tell me what you though what your misconfiguration was? Generally the extension should renders the complete page content.

**Comment by Hobokens** [comment]
@marvinhuebner, @danielmaier42  There is not much to tell about my "misconfiguration". It was a stupid mistake on my part. I inserted an HML content element with divs and classes into my one pager to see if they were displayed correctly. When I later reopened my installation and  and everything was displayed correctly, I thought for a moment that the BE layout would be responsible. That's all - it was too late at night.
If you want, I can give you access to the installation via PM.

**Comment by h3nn3s** [comment]
@Hobokens Does your problem still occur? I cannot reproduce it on my 9 LTS installation.
If yes, could you please give some more information on how to reproduce?

**Comment by Hobokens** [comment]
@h3nn3s thanks for maintaining this extension in the future. I didn't check the problem again since my last comment. But I will do in the future and then inform you about the result.

**Comment by h3nn3s** [comment]
Hi @Hobokens,
thank you for the detailled informations. I will recheck what is happening. Really sounds like an annoying bug, I think in general this should be possible...

**Comment by h3nn3s** [comment]
Hi @Hobokens 
I rechecked this and can conform, that it is currently not possible.
There is completly no information about `layout` or `backend_layout` transfered to the Frontend output. This would be a nice enhancement. 

Currently I am unable to implement such a feature and btw. lacking an idea how to do so.
Would be nice if you mayby could bring a Pull Request?

**Comment by Hobokens** [comment]
Hi @h3nn3s,
thanks for your check. Unfortunately I'm just an experienced TYPO3 Integrator, that's why I can't help you.

**Comment by h3nn3s** [comment]
@Hobokens 
Are you willing to sponsor solving this issue? 
For me personally this issue has no priority at the moment because of missing an use-case

**Comment by Hobokens** [comment]
@h3nn3s 
Thanks for asking. I have decided to use the extension container. So I'm not missing backend layouts right now. That's why I close this issue.
