### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by matthaa** [bergwerk/bwrk_onepage#31]
Hello,
in my TYPO3 8.7.19 with bwrk_onepage 3.1.3 localization does not work. Gridelements (8.2.3) is installed but even data record that do not use gridelements always appear in the default language. Language configuration itself is correct I guess, pages and data records are translated correctly, e.g. menu items appear in the frontend in the selected language as expected.
Thanks for any hint or fix,
Matthias

**Comment by matthaa** [comment]
got it ;-)
config.sys_language_overlay = 1
is needed.

**Comment by marvinhuebner** [comment]
Hey @matthaa,

so it wasn't a bug from the onpage extension?

Thanks for the info, i will close this issue now.

**Comment by matthaa** [comment]
not at all - only a bug in my Typoscript ;-)
