### ISSUE TITLE
Update to TYPO3 9.5

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#37]
Hi,
are there any plans to update the extension?

Regards
Hobokens

**Comment by h3nn3s** [comment]
With PR #34 there is a compat-fix waiting for review and hopefully merge

**Comment by Hobokens** [comment]
Thanks for the fix. It would be wonderful if they would merge it soon.

**Comment by KonstantinSoelch** [comment]
Hi @Hobokens,

apparently we will not be maintaining this extension any further.

For more information you can look into a twitter post by one of my colleagues:
https://twitter.com/Marvin_Huebner/status/1145611396895428609

We are currently looking for a new maintainer, so if anybody is interested please let us know.

**Comment by h3nn3s** [comment]
Hi @Hobokens 
I took over maintanence from the Bergwerk guys and merged my compat-fix.
Github Version so is already fully working on TYPO3 9 LTS. 
Public release to TER will follow, stay tuned.
