### ISSUE TITLE
Class ContentRepository does not exist

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#47]
Installing the extension v.4.0 in a  TYPO3 9.5.16 installation I get the following error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1278450972: Class ContentRepository does not exist. Reflection failed. | TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException thrown in file /www/htdocs/w0144cf7/my-domain.de/typo3_src-9.5.16/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php in line 363.`

**Comment by h3nn3s** [comment]
@Hobokens 
Can you please verify, that this is not an autoloading-issue?

**Comment by h3nn3s** [comment]
If it is an autoloading issue, please check if latest release of 4.0.1 solves the issue for you.

HTH Henrik

**Comment by Hobokens** [comment]
I'm sorry. I still problem is still there.
Regards
Hobokens

**Comment by h3nn3s** [comment]
New version 4.0.2 got released and should appear in a few minutes also in TER.
Sorry for the problems caused in 9.5

**Comment by Hobokens** [comment]
Thanks a lot. This solved the problem for me.
