### ISSUE TITLE
hide child content elemnts created width flux

### ISSUE THREAD

**Issue by milanffm** [bergwerk/bwrk_onepage#5]
if you have child element created width flux, they are shown twice on the page.

can you please add something like this to the "ContentRepository.php":

```php
 if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('flux')) {
            $constraints[] = $query->equals("tx_flux_parent", 0);
        }
```

**Comment by BERGWERK-User** [comment]
thanks for your addition. it was added in v3.0.8 :-)
