### ISSUE TITLE
TYPO3 11.5.

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#52]
Hi,
do you plan to upgrade the extension to the next LTS?

Regards
Hobokens

**Comment by h3nn3s** [comment]
Hi,
due to lack of time and a concrete project it is not planned for 2021.

Kind regards
Henrik

**Comment by Hobokens** [comment]
Hi,
thanks for the fast reply. 
Kind regards
Hobokens

**Comment by h3nn3s** [comment]
v5 is compatible with TYPO3 11 LTS now

**Comment by Hobokens** [comment]
Thanks!
