### ISSUE TITLE
double menu v 5.0.2

### ISSUE THREAD

**Issue by Hobokens** [bergwerk/bwrk_onepage#53]
Hi,
thanks for upgrading the extension. But now I get the menu for links with class 'section_page' twice. Only the menu link with class "bwrk-onepage-external" is single.

Regards
Hobokens

**Comment by h3nn3s** [comment]
Sorry, but I definitly cannot reproduce this on v11.
I think I had an similar issue after upgrading. You cleared all cached, I think?

To reproduce this issue I need some more informations.

Regards,
Henrik

**Comment by Hobokens** [comment]
Of course, I cleared all caches. :-)
 I get the double menu with v10.4.21. I'm just starting to upgrade the side.

**Comment by Hobokens** [comment]
I just did an upgrade to 11.5.7 and still get a double menu and a double content.
Regards
Hoboken

**Comment by Hobokens** [comment]
Removing the setting 'Show Page-Titles' in the extension solved the problem.
Regards 
Hobokens
