### ISSUE TITLE
Compatibility with typo3 version 12?

### ISSUE THREAD

**Issue by contentsign** [bergwerk/bwrk_onepage#55]
Is the compatibility with typo3 12 on your roadmap, or is this an abandoned extension?

**Comment by h3nn3s** [comment]
Hi, 
nowaday I am not using this extension anymore.
Further, I did not test it with v12 yet to see how many things needs to be fixed.

PR is highly appreciated so.

**Comment by h3nn3s** [comment]
Closed with #58
