### ISSUE TITLE
problems with multlingual rendering

### ISSUE THREAD

**Issue by webyourlife** [bergwerk/bwrk_onepage#7]
hi, we're using your onpage-EXT in some pages but today we got this problem:
some images in second language are not rendered correctly; everything else seems to be good

now we looked into the code and found this:
every item gets the id of the english item - even if language should be german (language-sys-id: en: 0 / de:1); titel of the section is translated but not so the texts, images ...

maybe it is a bug that the source-id is used and not the id of the translated one? in the image you can find id 88 as well in english and in german - in german version the translated id has the id 234.

![bug_bwrkonepage](https://cloud.githubusercontent.com/assets/17027337/12753211/6db70266-c9c6-11e5-9afb-ef4e62677651.jpg)

thanks for reviewing
joachim

**Comment by webyourlife** [comment]
Found the solution - content is not rendered in neccecary language:

/typo3conf/ext/bwrk_onepage/Classes/Domain/Model/Content.php

```
     /**
     * _localizedUid
     * @var string
     */
    protected $_localizedUid;

    /**
     * Returns the _localizedUid
     *
     * @return string $_localizedUid
     */
    public function get_localizedUid() {
        return $this->_localizedUid;
    }
```


/typo3conf/ext/bwrk_onepage/Classes/Controller/OnepageController.php
Line 107:
```
    'uid' => $contentElement->getUid(),
```
replaced by
```
    'uid' => $contentElement->get_localizedUid()
```

**Comment by BERGWERK-User** [comment]
thanks for your fix!
it was added in v3.0.9
